version: '3.7'

services:
  api: &api
    container_name: pennylane-api
    image: pennylane-api
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ["sh", "docker-entrypoint.sh"]
    command: ["rails", "server", "-p", "3000", "-b", "0.0.0.0"]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - "./:/opt/app"
    depends_on:
      - db

  api_slim:
    << : *api
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    ports:
      - 5432
    env_file: .env

  docs:
    image: "redocly/redoc:v2.0.0-rc.22"
    ports:
      - "8080:80"
    volumes:
      - ./docs/v1/open-api-spec.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      - SPEC_URL=swagger.yaml

  openapi2schema:
    build: "docs/openapi2schema/"
    command: "-p -i ~/v1/open-api-spec.yaml"
    volumes:
      - './docs/v1:/~/v1'
